import { Container, Header } from "@/shared/components/shared";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Next Pizza | Корзина",
  description: "Generated by Next.js",
};

export default function CheckoutLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="min-h-screen bg-background">
      <Container>
        <Header
          hasSearch={false}
          hasCart={false}
          className="border-b-secondary"
        />
        {children}
      </Container>
    </main>
  );
}
