import { Container, Header } from "@/shared/components/shared";
import { Metadata } from "next";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Sport Shop | Корзина",
  description: "Generated by Next.js",
};
// изменил suspense
export default function CheckoutLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="min-h-screen bg-background">
      <Container>
        <Suspense>
          <Header
            hasSearch={false}
            hasCart={false}
            className="border-b-secondary"
          />
        </Suspense>
        {children}
      </Container>
    </main>
  );
}
